# Jekyll Config
# Variables defined here will be accessible in the templates via
# {{ site.myvariable }}.

# Site
title: BaseWeb
version: 2.3.2
description: >
  BaseWeb is a fresh SCSS front-end development framework and library built to
  help keep your projects simple, organized and responsive.
baseurl: ""
url: "http://getbaseweb.com"
author: Sebastian Nitu
author_url: http://sebnitu.com
author_email: me@sebnitu.com
twitter_username: sebnitu
github_username: sebnitu

# Build
markdown: kramdown
kramdown:
  auto_ids: true

# Server
source: docs
destination: _site
# permalink: pretty
host: localhost
port: 8080
exclude: [
  'src',
  'LICENSE'
]

# Custom
repository:
  type : git
  url  : https://github.com/sebnitu/BaseWeb.git
packages:
  src: https://github.com/sebnitu/BaseWeb/tree/master/src
  dist: https://github.com/sebnitu/BaseWeb/tree/master/dist
