# Jekyll Config
# Variables defined here will be accessible in the templates via
# {{ site.myvariable }}.

# Site
title: BaseWeb
version: 2.3.3
description: >
  BaseWeb is a fresh SCSS front-end development framework and library built to
  help keep your projects simple, organized and responsive.
baseurl: "/BaseWeb" # the subpath of your site, e.g. /blog
url: "http://sebnitu.com" # base hostname & protocol for your site
author: Sebastian Nitu
author_url: http://sebnitu.com
author_email: me@sebnitu.com
twitter_username: sebnitu
github_username: sebnitu

# Build
markdown: kramdown
kramdown:
  auto_ids: true

# Server
source: docs
destination: _site
# permalink: pretty
host: localhost
port: 8080
exclude: ['src']

# Other
gems: ['jekyll-github-metadata']
repository: sebnitu/BaseWeb
