name: BaseWeb
version: 2.2.4
author: Sebastian Nitu
url: http://sebnitu.com
repository:
  type : git
  url  : https://github.com/sebnitu/BaseWeb.git
packages:
  src: https://github.com/sebnitu/BaseWeb/tree/master/src
  dist: https://github.com/sebnitu/BaseWeb/tree/master/dist
