# Server
host: localhost
port: 8080
baseurl: "" # subpath of your site, e.g. /blog
url: "http://getbaseweb.com" # base hostname & protocol for your site
permalink: pretty

# Site
markdown: kramdown
title: BaseWeb
description: "A light UI component library built to make web projects faster, flexible and easier to maintain."
version: 3.0.4
repository: sebnitu/BaseWeb

exclude:
  - node_modules
  - src

# Plugins
plugins:
  - jekyll-feed
  - jekyll-github-metadata

# Author
author:
  name: Sebastian Nitu
  url: http://sebnitu.com
  email: me@sebnitu.com
  twitter: sebnitu

# Defaults
defaults:
  - scope:
      path: ''
    values:
      layout: page

  - scope:
      path: '_posts'
      type: 'posts'
    values:
      layout: post
      category: blog
