# Server settings
###

host: localhost
port: 8020
baseurl: '' # subpath of your site, e.g. /blog
url: 'https://getbaseweb.com' # base hostname & protocol for your site

# Site details
###

title: BaseWeb
version: 3.0.6
description: "A light UI component library built to make web projects faster, flexible and easier to maintain."
email: me@sebnitu.com
repository: sebnitu/BaseWeb

# Build settings
###

permalink: pretty
plugins:
  - jekyll-feed
exclude:
  - node_modules
  - src
  - Gemfile
  - Gemfile.lock
  - gulpfile.babel.js
  - package-lock.json
  - package.json
  - readme.md

# Defaults
defaults:
  - scope:
      path: ''
      type: 'posts'
    values:
      category: blog

# Theme settings
###

# Third-party
google_analytics: UA-5911557-6
