# Jekyll Config
# Variables defined here will be accessible in the templates via
# {{ site.myvariable }}.

# Site
title: BaseWeb
version: 2.3.6
description: >
  BaseWeb is a fresh SCSS front-end development framework and library built to
  help keep your projects simple, organized and responsive.
baseurl: "" # subpath of your site, e.g. /blog
url: "http://getbaseweb.com" # base hostname & protocol for your site
repository: sebnitu/BaseWeb
author: Sebastian Nitu
author_url: http://sebnitu.com
author_email: me@sebnitu.com

# Build
markdown: kramdown
kramdown:
  auto_ids: true
permalink: pretty
gems: ['jekyll-github-metadata']

# Server
host: localhost
port: 8080
exclude: ['src']
