# Jekyll Config
# Variables defined here will be accessible in the templates via
# {{ site.myvariable }}.

# Site
title: BaseWeb
version: 2.6.4
baseurl: "" # subpath of your site, e.g. /blog
url: "http://getbaseweb.com" # base hostname & protocol for your site
repository: sebnitu/BaseWeb
author: Sebastian Nitu
author_url: http://sebnitu.com
author_email: me@sebnitu.com
author_twitter: sebnitu

# Build
markdown: kramdown
permalink: pretty
plugins:
- jekyll-github-metadata

# Server
host: localhost
port: 8080

# Removes files and folders from jekyll build
exclude:
- src
